apiVersion: v1
kind: ConfigMap
metadata:
  name: finscheduler-api-config
data:
  ENV: LocalKubernetes
  SERVER_PORT: "8080"
  OBSERVABILITY_SERVICE_NAME: fin-scheduler-api
  METRICS_ENABLED: "true"
  METRICS_EXPORT_ENDPOINT: /metrics
  TRACES_ENABLED: "true"
  TRACES_EXPORT_ENDPOINT: http://tempo:4318/v1/traces
  TRACES_ROOT_TRACE_SAMPLING_RATIO: "1"
  PROFILING_ENABLED: "false"
  PROFILING_PUSH_URL: http://pyroscope:4040
  CORS_ALLOWED_ORIGINS: "*"
  CORS_ALLOWED_METHODS: GET,POST,PUT,DELETE,OPTIONS
  CORS_ALLOWED_HEADERS: "*"
  CORS_ALLOW_CREDENTIALS: "false"
