apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - loki-deployment.yaml
  - loki-service.yaml
  - alloy-serviceaccount.yaml
  - alloy-clusterrole.yaml
  - alloy-clusterrolebinding.yaml
  - alloy-deployment.yaml
  - grafana-admin-secret.yaml
  - grafana-db-secret.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml
configMapGenerator:
  - name: alloy-logs-config
    files:
      - config.alloy=alloy/config.alloy
  - name: grafana-datasources
    files:
      - datasources.yml=grafana/datasources.yml
  - name: loki-config
    files:
      - loki.yml=loki/loki.yml
generatorOptions:
  disableNameSuffixHash: true
