apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - admin-secret.yaml
  - db-secret.yaml
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: grafana-datasources
    files:
      - datasources.yml=datasources.yml
generatorOptions:
  disableNameSuffixHash: true
