apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finscheduler
spec:
  rules:
    - host: www.finscheduler.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: finscheduler-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: finscheduler-web
                port:
                  number: 80
    - host: grafana.finscheduler.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
