apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: pyroscope-config
    files:
      - pyroscope.yaml=pyroscope.yaml
generatorOptions:
  disableNameSuffixHash: true
